version: '3.3'
services:
  web:
    image: ${DOCKER_IMAGE}
    ports:
      - "${PORT}:${PORT}"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: ${DOCKER_IMAGE}
        
  elasticsearch:
    image: elasticsearch:7.5.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    restart: on-failure


  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - /var/log:/var/log
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  kibana:
    image: kibana:7.5.0
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601
    restart: on-failure
